export const GETALLCOUNTRIES = "GET_ALL_COUNTRIES";
export const POSTACTIVITY = "POST_ACTIVITY"
export const GETCOUNTRYDETAIL= "GET_COUNTRY_DETAIL"
export const GETACTIVITIES= "GET_ACTIVITIES"
export const ALLFILTERS= "ALL_FILTERS"