export const GETALLCOUNTRIES = "GET_ALL_COUNTRIES";
export const FILTERBYCONTINENT = "FILTER_BY_CONTINENT";
export const ORDERBYCOUNTRYNAME = "ORDER_BY_COUNTRY_NAME"
export const ORDERBYCOUNTRYPOPULATION = "ORDER_BY_COUNTRY_POPULATION"
export const GETCOUNTRYBYNAME = "GET_COUNTRY_BY_NAME"
export const POSTACTIVITY = "POST_ACTIVITY"
export const GETCOUNTRYDETAIL= "GET_COUNTRY_DETAIL"